// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package user

import (
	"time"
)

type UserInput struct {
	Age       int        `json:"age"`
	Birthday  *time.Time `json:"birthday"`
	Names     string     `json:"names"`
	Lastnames string     `json:"lastnames"`
	Activate  bool       `json:"activate"`
}
