// Code generated by entc, DO NOT EDIT.

package ent

import (
	"github.com/amaru0601/go-rent/ent/schema"
	"github.com/amaru0601/go-rent/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescAge is the schema descriptor for age field.
	userDescAge := userFields[0].Descriptor()
	// user.AgeValidator is a validator for the "age" field. It is called by the builders before save.
	user.AgeValidator = userDescAge.Validators[0].(func(int) error)
	// userDescNames is the schema descriptor for names field.
	userDescNames := userFields[1].Descriptor()
	// user.NamesValidator is a validator for the "names" field. It is called by the builders before save.
	user.NamesValidator = userDescNames.Validators[0].(func(string) error)
	// userDescLastnames is the schema descriptor for lastnames field.
	userDescLastnames := userFields[2].Descriptor()
	// user.LastnamesValidator is a validator for the "lastnames" field. It is called by the builders before save.
	user.LastnamesValidator = userDescLastnames.Validators[0].(func(string) error)
}
