// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Property is the predicate function for property builders.
type Property func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
